In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))

In [ ]:
# Showing difference in Execution Times for normal Python Lists VS numpy arrays
# range function does not return a List in Python-3, but in Python-2 it did. In Python-3 it returns a range object - much like a number generator, it creates the next number only when explicitly told to do so - like in a Loop, or by passing the whole range(n) to list() function
import time

SIZE = 10_000_000

# Python List
originalList = list(range(SIZE)) # [0, 1, 2, 3, 4, ........ , 10_000_000-1]              
start = time.time()
squareList = [x**2 for x in originalList]
end = time.time()
print(f"Python List Process took {end-start} seconds.")

# Numpy array
npArray = np.array(originalList)
start = time.time()
squareArray = npArray ** 2
end = time.time()
print(f"Numpy Process took {end-start} seconds.")




In [ ]:
# Showing immense memory efficiency of numpy arrays over Python Lists, as they store homogenous data in contiguos blocks and no Memory overhead due too meta-data
import sys
print(f"Size of Python SquareList: {sys.getsizeof(squareList)} bytes.")
print(f"Size of Numpy SquareArray: {npArray.nbytes} bytes.")

In [ ]:
# Creating Numpy Arrays

# From Python Lists - 1D - Each element is counted as a Row
arr1 = [1, 2, 3, 4, 5] # Homegenous lists
myNumPyArray1 = np.array(arr1)
print(myNumPyArray1, myNumPyArray1.dtype, myNumPyArray1.shape) # Prints the numpy array, and its data type is int64

arr2 = [1, 2, 3, 4, "Sonu", True] # Heterogenous Lists
myNumPyArray2 = np.array(arr2) # converts everything to string
print(myNumPyArray2, myNumPyArray2.dtype, myNumPyArray2.shape) # dtype is Unicode format 21 (U21) for strings

# Creating 2-D Numpy Arrays from 2D Lists - Each inner List is counted as a Row
list2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
npArray2D = np.array(list2D)
print(f"Shape of 2D Numpy array is {npArray2D.shape}.")
# Proper rectangular dimension is necessary - below code will THROW ERROR due to inhomegenous shape !!!
#list2D_nonShaped = np.array([[1, 2, 3], [4, 5, 6, 999], [7, 8, 9], [10, 11, 12]])
# print(list2D_nonShaped.shape)

In [ ]:
# Creating numpy arrays from scratch
npArr = np.zeros((2, 4), dtype="int64") # Prefill with zeroes
print(npArr, npArr.shape)

npArr = np.ones((4,)) # Prefill with 1s -> 4 rows and 1 column, default dtype is float
print(npArr, npArr.shape)

npArr = np.full((5, 3), fill_value=56) # Prefill with fill_value, 5 rows and 3 columns, dtype is of fill_value
print(npArr, npArr.shape)

npArr = np.eye(5, dtype="int64") # Makes a Identity Matrix (Always square) of size 5
print(npArr, npArr.shape)

npArr = np.arange(1, 11, 1, dtype=int) # Makes a Numpy array with ranged elements - Notice the spelling of arange !!! Not double 'r'
print(npArr, npArr.shape)

npArr = np.linspace(1, 100, 3, dtype="int64") # Create evenly spaced arrays - as there are 3 elements from 1 to 100, and size should be 3, mid element should be 50. end is included here.
# so numbers will be 1, 50 and 100.
print(npArr, npArr.shape)



In [ ]:
# Properties of numpy arrays
print(npArr.ndim) # dimensions
print(npArr.dtype) # data type
print(npArr.size) # total elements
print(npArr.shape)

# Create a different numpy array with a different type using an already existing npArray
npArrFloat = npArr.astype(np.float64)
print(npArrFloat, npArray2D.dtype)

##### Operations on NumPy Arrays

In [ ]:
# Reshaping - No. of elements should be compatible
original = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = original.reshape((3, 2))
reshaped2 = original.reshape((1,6))
reshaped3 = original.reshape((6, 1)) # 2D Vector - contains 6 rows and 1 column, where 1 column holds individual elements.
print(original, original.shape)
print(reshaped, reshaped.shape)
print(reshaped2, reshaped2.shape)
print(reshaped3, reshaped3.shape)

# Flattening - convert to 1D array
flattened = original.flatten() # 1D Array - NOT A VECTOR, though it shows 6 rows and 1 column. It practically has no columns. Each number is a column.
print(flattened, flattened.shape)


In [ ]:
# Normal Indexing

original = np.array([[1, 2, 3], [4, 5, 6]])
flattened = original.flatten()
print(original[1][2])
print(flattened.shape) # It will show 6 rows, 1 column
# print(flattened[5][0]) # It will throw error, because though in our eyes it's a single row matrix, and even .shape() gives (6,) it's a 1D Array inside numpy. So we have to use only row number, col number is default 0.
print(flattened[5])
# But if we change the shape explicity, it's a 2D Vector ! - .shape() gives (6, 1)

# MIND THAT (6,) represents a 1D array along SINGLE dimension, but (6,1) is a Vector 2D array, along 2 dimensions !🫠
# Though they might look same, they are different types in NumPy.
specialFlattened = original.reshape(6, 1)
print(specialFlattened[5][0])

In [ ]:
# Fancy indexing 1D Arrays
indices = [1, 3]
print(flattened[indices])

original = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

# Fancy indexing 2D Vectors
rows = [0, 1, 1]
cols = [2, 1, 0]
print(original[rows, cols]) # Grabs [0][2]->3, [1][1]->5 and [1][0]->4

In [ ]:
# Boolean Indexing

original = np.array([[1, 2, 3], [4, 5, 6]])
flattened = original.flatten()
print(flattened[flattened % 2 == 0]) # Returns 1D array
print(original[original % 2 != 0]) # Returns 1D array

In [ ]:
# Slicing
original = np.array([[1, 2, 3], [4, 5, 6]])
flattened = original.flatten() 
print(flattened[1:4]) # 2, 3, 4
print(flattened[2:]) # 3 4 5 6 
print(flattened[:4]) # 1 2 3 4
print(flattened[::2]) #1 3 5
print(flattened[::-1]) # Reverse the array

print(original[1::][0:3]) # [[4 5 6]] - From row index 1 to end, all columns
# starting from 1 in inner slice won't work as number of rows are 1, and row indices start from 0.


In [ ]:
# =================================================================
# 1. IMMUTABLE TYPES (Integers, Strings, Tuples)
# LOGIC: Python is 'Pass-by-Object-Reference'. 
# Everything is a pointer. But since you can't 'edit' the number 10, 
# any 'change' forces the pointer to move to a new number.
# This BEHAVES like 'Pass-by-Value' even though it's technically a reference.
# =================================================================
a = 10
b = a  # Both point to the same '10' object
b = 20 # b can't change '10', so it rebinds to a NEW object '20'

print("--- Immutable (Feels like Pass-by-Value) ---")
print(f"a: {a}, b: {b}") # a is still 10. The original was never touched.

# =================================================================
# 2. MUTABLE TYPES (Lists)
# LOGIC: Here, the 'Reference' behavior is obvious. 
# The box is changeable, so all labels pointing to it see the edits.
# =================================================================
list_orig = [1, 2, 3]

# ASSIGNMENT (=): Pass-by-Reference behavior. Both names share the box.
list_assign = list_orig 
list_assign[0] = 99 

# SLICING ([:]): Manual Shallow Copy. 
# Breaks the reference by creating a brand new box.
list_slice = list_orig[:] 
list_slice[0] = 77 

print("\n--- Mutable (Classic Pass-by-Reference Behavior) ---")
print(f"Original: {list_orig}")   # Changed to [99, 2, 3]
print(f"Sliced:   {list_slice}")  # Independent [77, 2, 3]

# =================================================================
# 3. NUMPY ARRAYS - The "Memory View" Trap
# LOGIC: NumPy is designed for BIG data. 
# To save RAM, it avoids copying even during slicing. 
# It passes a 'View' (a window) to the original reference.
# =================================================================
np_orig = np.array([1, 2, 3])

# SLICING ([:]): In standard Python this copies, in NumPy this is a VIEW.
# It is still Pass-by-Reference!
np_view = np_orig[:] 

# EXPLICIT COPY (.copy()): The only way to truly 'Pass-by-Value'.
np_copy = np_orig.copy()

np_view[0] = 500 # Modifies the original data buffer!

print("\n--- NumPy (Performance-driven Reference) ---")
print(f"Original: {np_orig}") # Now [500, 2, 3]
print(f"Copy:     {np_copy}") # Safe

In [ ]:
# Creating arrays with specific NumPy dtypes
# =================================================================

# 1. Integers (Signed & Unsigned)
int_8   = np.array([127, -128], dtype=np.int8)     # 1 byte: -128 to 127
uint_8  = np.array([0, 255], dtype=np.uint8)       # 1 byte: 0 to 255 (Perfect for Images!)
int_32  = np.array([2**31 - 1], dtype=np.int32)    # 4 bytes: Standard integer
int_64  = np.array([2**63 - 1], dtype=np.int64)    # 8 bytes: Large integer / Pointers

# 2. Floats (Precision vs Speed)
float_16 = np.array([3.14], dtype=np.float16)      # 2 bytes: Half precision (AI edge devices)
float_32 = np.array([3.14159], dtype=np.float32)   # 4 bytes: Standard for Deep Learning
float_64 = np.array([3.14159265], dtype=np.float64)# 8 bytes: Standard for high-precision Physics

# 3. Specialized Types
bool_arr    = np.array([True, False], dtype=np.bool_)             # Boolean (1 byte)
complex_arr = np.array([1 + 2j, 3 - 4j], dtype=np.complex128)      # Complex numbers
str_arr     = np.array(["Drone", "Robot"], dtype=np.str_)         # Fixed-length Unicode
obj_arr     = np.array([{"id": 1}, [1, 2]], dtype=object)          # Pointers to Python objects

# =================================================================
# ROBOTICS SCENARIO: The "Small Data" Advantage
# =================================================================
# Scenario: Real-time Grayscale Image Processing on a Drone.
#
# A Grayscale image is essentially a 2D matrix where each pixel is between 0-255.
# If you use int64 (8 bytes per pixel) instead of uint8 (1 byte per pixel):
# 1. Memory Usage: You use 8x more RAM. 
# 2. Cache Misses: Your CPU Cache can hold 8 times fewer pixels at once.
# 3. Bandwidth: Transferring images from the Camera to the CPU takes 8x longer.
#
# For a 1080p stream, uint8 uses ~2MB per frame, while int64 uses ~16MB. 
# In high-speed robotics, uint8 is the difference between 60 FPS and 5 FPS.
# =================================================================

print(f"uint8 size: {uint_8.nbytes} bytes")
print(f"int64 size: {int_64.nbytes} bytes")

# Heterogenous numpy arrays are simply converted to Objects
het_arr = np.array([1, 
                    67.45, 
                    "Sonu", # <U32 String
                    {'name':"Sonu", 'age':23}
                    ])
print(het_arr, het_arr.dtype) # [1 67.45 'Sonu' {'name': 'Sonu', 'age': 23}] object

#### Multi-Dimensional Arrays

In [ ]:
# 2D Arrays
print("------------------------- 2D Arrays ------------------------- ")
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print(arr_2d)
print(np.sum(arr_2d))
print(np.sum(arr_2d, axis=0)) # 0 represents Rows, Axis 0 tells to Calculate in the direction of Rows->Vertically, Column-wise Sum, gives a 1D Array
print(np.sum(arr_2d, axis=1)) # 1 represents Columns, Axis 1 tells to Calculate in the direction of Columns->Horizontally, Row-Wise Sum
# Slicing 2D Arrays
print(arr_2d[1:3 , 2:3])








In [34]:
# import numpy as np

# 3D Array Setup: (Layers, Rows, Columns)
r = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
g = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
b = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]])

img = np.array([r, g, b])

print("="*90)
print("1. INDEXING & SLICING IN 3D")
print("="*90)

# Direct Indexing
# Structure: [Layer, Row, Col]
val = img[2, 1, 2] 
print(f"Element at [2,1,2] (Blue Layer, 2nd Row, 3rd Col): {val}\n")

# Slicing
# Structure: [All Layers, 0:2 Rows, 0:2 Cols]
corners = img[:, :2, :2]
print(f"Top-Left 2x2 Corners for all color channels:\n{corners}\n")

print("="*90)
print("2. SINGLE LAYER SUMMING (2D Logic), No axis specified for Layer, it as accessed as img[<layer_index>]")  
print("="*90)

# img[1] is the Green Layer (2D). 
# axis=0 here means 'move down the rows' -> Result: Column Sums
sum_green_cols = np.sum(img[1], axis=0) 
print(f"Green Layer - Sum of each Column: {sum_green_cols}")

# img[2] is the Blue Layer (2D). 
# axis=1 here means 'move across the columns' -> Result: Row Sums
sum_blue_rows = np.sum(img[2], axis=1) 
print(f"Blue Layer - Sum of each Row:    {sum_blue_rows}\n")

print("="*90)
print("3. GLOBAL AXIS SUMMING (3D 'Smash' Logic), Layer uses Axis = 0 this time")
print("="*90)

# Axis 0: Direction of LAYERS (Depth)
# Logic: Smash R + G + B. Result is a 2D image.
sum_depth = np.sum(img, axis=0)
print(f"Axis 0 (Depth Smash / Channel-wise Sum):\n{sum_depth}\n")

# Axis 1: Direction of ROWS (Vertical)
# Logic: Squash each layer vertically. Result: Column totals per layer.
sum_vert = np.sum(img, axis=1)
print(f"Axis 1 (Vertical Squash / Column-wise Sums):\n{sum_vert}\n")

# Axis 2: Direction of COLUMNS (Horizontal)
# Logic: Squash each layer horizontally. Result: Row totals per layer.
sum_horiz = np.sum(img, axis=2)
print(f"Axis 2 (Horizontal Squash / Row-wise Sums):\n{sum_horiz}\n")

print("="*90)
print("4. MULTI-AXIS SUMMING")
print("="*90)

# axis=(0, 1): Smash Depth AND then smash the resulting Rows.
# Only the Column dimension (Axis 2) survives.
sum_multi = np.sum(img, axis=(0, 1))
print(f"Multi-Axis (0, 1) - Total weight of each Vertical Column: {sum_multi}")

1. INDEXING & SLICING IN 3D
Element at [2,1,2] (Blue Layer, 2nd Row, 3rd Col): 600

Top-Left 2x2 Corners for all color channels:
[[[  1   2]
  [  4   5]]

 [[ 10  11]
  [ 13  14]]

 [[100 200]
  [400 500]]]

2. SINGLE LAYER SUMMING (2D Logic), No axis specified for Layer, it as accessed as img[<layer_index>]
Green Layer - Sum of each Column: [39 42 45]
Blue Layer - Sum of each Row:    [ 600 1500 2400]

3. GLOBAL AXIS SUMMING (3D 'Smash' Logic), Layer uses Axis = 0 this time
Axis 0 (Depth Smash / Channel-wise Sum):
[[111 213 315]
 [417 519 621]
 [723 825 927]]

Axis 1 (Vertical Squash / Column-wise Sums):
[[  12   15   18]
 [  39   42   45]
 [1200 1500 1800]]

Axis 2 (Horizontal Squash / Row-wise Sums):
[[   6   15   24]
 [  33   42   51]
 [ 600 1500 2400]]

4. MULTI-AXIS SUMMING
Multi-Axis (0, 1) - Total weight of each Vertical Column: [1251 1557 1863]
