In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
# Showing difference in Execution Times for normal Python Lists VS numpy arrays
# range function does not return a List in Python-3, but in Python-2 it did. In Python-3 it returns a range object - much like a number generator, it creates the next number only when explicitly told to do so - like in a Loop, or by passing the whole range(n) to list() function
import time

SIZE = 10_000_000

# Python List
originalList = list(range(SIZE)) # [0, 1, 2, 3, 4, ........ , 10_000_000-1]              
start = time.time()
squareList = [x**2 for x in originalList]
end = time.time()
print(f"Python List Process took {end-start} seconds.")

# Numpy array
npArray = np.array(originalList)
start = time.time()
squareArray = npArray ** 2
end = time.time()
print(f"Numpy Process took {end-start} seconds.")




Python List Process took 0.6450886726379395 seconds.
Numpy Process took 0.028281211853027344 seconds.


In [4]:
# Showing immense memory efficiency of numpy arrays over Python Lists, as they store homogenous data in contiguos blocks and no Memory overhead due too meta-data
import sys
print(f"Size of Python SquareList: {sys.getsizeof(squareList)} bytes.")
print(f"Size of Numpy SquareArray: {npArray.nbytes} bytes.")

Size of Python SquareList: 89095160 bytes.
Size of Numpy SquareArray: 80000000 bytes.


In [5]:
# Creating Numpy Arrays

# From Python Lists - 1D - Each element is counted as a Row
arr1 = [1, 2, 3, 4, 5] # Homegenous lists
myNumPyArray1 = np.array(arr1)
print(myNumPyArray1, myNumPyArray1.dtype, myNumPyArray1.shape) # Prints the numpy array, and its data type is int64

arr2 = [1, 2, 3, 4, "Sonu", True] # Heterogenous Lists
myNumPyArray2 = np.array(arr2) # converts everything to string
print(myNumPyArray2, myNumPyArray2.dtype, myNumPyArray2.shape) # dtype is Unicode format 21 (U21) for strings

# Creating 2-D Numpy Arrays from 2D Lists - Each inner List is counted as a Row
list2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
npArray2D = np.array(list2D)
print(f"Shape of 2D Numpy array is {npArray2D.shape}.")
# Proper rectangular dimension is necessary - below code will THROW ERROR due to inhomegenous shape !!!
#list2D_nonShaped = np.array([[1, 2, 3], [4, 5, 6, 999], [7, 8, 9], [10, 11, 12]])
# print(list2D_nonShaped.shape)

[1 2 3 4 5] int64 (5,)
['1' '2' '3' '4' 'Sonu' 'True'] <U21 (6,)
Shape of 2D Numpy array is (4, 3).


In [6]:
# Creating numpy arrays from scratch
npArr = np.zeros((2, 4), dtype="int64") # Prefill with zeroes
print(npArr, npArr.shape)

npArr = np.ones((4,)) # Prefill with 1s -> 4 rows and 1 column, default dtype is float
print(npArr, npArr.shape)

npArr = np.full((5, 3), fill_value=56) # Prefill with fill_value, 5 rows and 3 columns, dtype is of fill_value
print(npArr, npArr.shape)

npArr = np.eye(5, dtype="int64") # Makes a Identity Matrix (Always square) of size 5
print(npArr, npArr.shape)

npArr = np.arange(1, 11, 1, dtype=int) # Makes a Numpy array with ranged elements - Notice the spelling of arange !!! Not double 'r'
print(npArr, npArr.shape)

npArr = np.linspace(1, 100, 3, dtype="int64") # Create evenly spaced arrays - as there are 3 elements from 1 to 100, and size should be 3, mid element should be 50. end is included here.
# so numbers will be 1, 50 and 100.
print(npArr, npArr.shape)



[[0 0 0 0]
 [0 0 0 0]] (2, 4)
[1. 1. 1. 1.] (4,)
[[56 56 56]
 [56 56 56]
 [56 56 56]
 [56 56 56]
 [56 56 56]] (5, 3)
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] (5, 5)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1  50 100] (3,)


In [7]:
# Properties of numpy arrays
print(npArr.ndim) # dimensions
print(npArr.dtype) # data type
print(npArr.size) # total elements
print(npArr.shape)

# Create a different numpy array with a different type using an already existing npArray
npArrFloat = npArr.astype(np.float64)
print(npArrFloat, npArray2D.dtype)

1
int64
3
(3,)
[  1.  50. 100.] int64


##### Operations on NumPy Arrays

In [8]:
# Reshaping - No. of elements should be compatible
original = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = original.reshape((3, 2))
reshaped2 = original.reshape((1,6))
reshaped3 = original.reshape((6, 1)) # 2D Vector - contains 6 rows and 1 column, where 1 column holds individual elements.
print(original, original.shape)
print(reshaped, reshaped.shape)
print(reshaped2, reshaped2.shape)
print(reshaped3, reshaped3.shape)

# Flattening - convert to 1D array
flattened = original.flatten() # 1D Array - NOT A VECTOR, though it shows 6 rows and 1 column. It practically has no columns. Each number is a column.
print(flattened, flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3 4 5 6]] (1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)
[1 2 3 4 5 6] (6,)


In [9]:
# Normal Indexing

original = np.array([[1, 2, 3], [4, 5, 6]])
flattened = original.flatten()
print(original[1][2])
print(flattened.shape) # It will show 6 rows, 1 column
# print(flattened[5][0]) # It will throw error, because though in our eyes it's a single row matrix, and even .shape() gives (6,) it's a 1D Array inside numpy. So we have to use only row number, col number is default 0.
print(flattened[5])
# But if we change the shape explicity, it's a 2D Vector ! - .shape() gives (6, 1)

# MIND THAT (6,) represents a 1D array along SINGLE dimension, but (6,1) is a Vector 2D array, along 2 dimensions !🫠
# Though they might look same, they are different types in NumPy.
specialFlattened = original.reshape(6, 1)
print(specialFlattened[5][0])

6
(6,)
6
6


In [10]:
# Fancy indexing 1D Arrays
indices = [1, 3]
print(flattened[indices])

original = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

# Fancy indexing 2D Vectors
rows = [0, 1, 1]
cols = [2, 1, 0]
print(original[rows, cols]) # Grabs [0][2]->3, [1][1]->5 and [1][0]->4

[2 4]
[3 5 4]


In [11]:
# Boolean Indexing

original = np.array([[1, 2, 3], [4, 5, 6]])
flattened = original.flatten()
print(flattened[flattened % 2 == 0]) # Returns 1D array
print(original[original % 2 != 0]) # Returns 1D array

[2 4 6]
[1 3 5]


In [ ]:
# Slicing
original = np.array([[1, 2, 3], [4, 5, 6]])
flattened = original.flatten() 
print(flattened[1:4]) # 2, 3, 4
print(flattened[2:]) # 3 4 5 6 
print(flattened[:4]) # 1 2 3 4
print(flattened[::2]) #1 3 5
print(flattened[::-1]) # Reverse the array

print(original[1::][0:3]) # [[4 5 6]] - From row index 1 to end, all columns
# starting from 1 in inner slice won't work as number of rows are 1, and row indices start from 0.


[2 3 4]
[3 4 5 6]
[1 2 3 4]
[1 3 5]
[6 5 4 3 2 1]
[[4 5 6]]


In [20]:
# =================================================================
# 1. IMMUTABLE TYPES (Integers, Strings, Tuples)
# LOGIC: Python is 'Pass-by-Object-Reference'. 
# Everything is a pointer. But since you can't 'edit' the number 10, 
# any 'change' forces the pointer to move to a new number.
# This BEHAVES like 'Pass-by-Value' even though it's technically a reference.
# =================================================================
a = 10
b = a  # Both point to the same '10' object
b = 20 # b can't change '10', so it rebinds to a NEW object '20'

print("--- Immutable (Feels like Pass-by-Value) ---")
print(f"a: {a}, b: {b}") # a is still 10. The original was never touched.

# =================================================================
# 2. MUTABLE TYPES (Lists)
# LOGIC: Here, the 'Reference' behavior is obvious. 
# The box is changeable, so all labels pointing to it see the edits.
# =================================================================
list_orig = [1, 2, 3]

# ASSIGNMENT (=): Pass-by-Reference behavior. Both names share the box.
list_assign = list_orig 
list_assign[0] = 99 

# SLICING ([:]): Manual Shallow Copy. 
# Breaks the reference by creating a brand new box.
list_slice = list_orig[:] 
list_slice[0] = 77 

print("\n--- Mutable (Classic Pass-by-Reference Behavior) ---")
print(f"Original: {list_orig}")   # Changed to [99, 2, 3]
print(f"Sliced:   {list_slice}")  # Independent [77, 2, 3]

# =================================================================
# 3. NUMPY ARRAYS - The "Memory View" Trap
# LOGIC: NumPy is designed for BIG data. 
# To save RAM, it avoids copying even during slicing. 
# It passes a 'View' (a window) to the original reference.
# =================================================================
np_orig = np.array([1, 2, 3])

# SLICING ([:]): In standard Python this copies, in NumPy this is a VIEW.
# It is still Pass-by-Reference!
np_view = np_orig[:] 

# EXPLICIT COPY (.copy()): The only way to truly 'Pass-by-Value'.
np_copy = np_orig.copy()

np_view[0] = 500 # Modifies the original data buffer!

print("\n--- NumPy (Performance-driven Reference) ---")
print(f"Original: {np_orig}") # Now [500, 2, 3]
print(f"Copy:     {np_copy}") # Safe

--- Immutable (Feels like Pass-by-Value) ---
a: 10, b: 20

--- Mutable (Classic Pass-by-Reference Behavior) ---
Original: [99, 2, 3]
Sliced:   [77, 2, 3]

--- NumPy (Performance-driven Reference) ---
Original: [500   2   3]
Copy:     [1 2 3]
